The great refactor (#31)
* upgrade to expo v38.0.4 lmao

* setValue Action

* expo install react-native-screens

* setup more actions

* clean up

* add eslint

* eslint final

* lint + lintf script

* change eslint parser to babel-eslint

* eslint --fix

* simplify about page

* refactored About page

instead of all those messy <Text> stuff, I made some helper functions. Hopefully this makes the settings page easier to modify.

Also note, "spacer" is not a function.

* remove dead code in Data.js

* last clean-up of tonight

I'm currently experiencing an error,

"TypeError: instance.render is not a function"

Since it's 1:40, I'll commit whatever I have now, and finish it in the morning.

* I swear last cleanup of the night

* fix random error

* install @reduxjs/toolkit@1.4.0

* npm audit fix

* starting the great redux into redux

* basic redux test! :smile:

success!

* structure of store.js

* getting into the flow of redux

* boolbutton dispatch test

- converted boolbutton to functional component
- no more global state BS
- temporarily breaks boolbutton functionality

* success! BoolButton refactored for Redux

* refactor numButton to use Redux

* partial radiobuttons redux refactor

* (broken) timer refactor

timer is broken, figure out why

* sorry, \r\n is cooler than \n

* panick

I can't do anything today, brain not working, I'll go to sleep now.

goodbye

* Fix Timer.js

Co-Authored-By: Whimpers <kryptocrashmh@gmail.com>

* Refactor ClimbHeight

* finishing touches on ClimbHeight

* refactored climbPosition

* prop-types

* npm update

* update react-native-safe-area-context

* replaced state with useSelector

really hoping I don't regret this decision

fueled by the desire to be able to modify state through the redux store, I'm mainly concerned about performance when it comes to text boxes.

I also added setDefault in dataSlice.

I'm already regretting keyPairValue, I should have just used a normal object. What was I thinking?

* refactor climbheight so it uses redux

now climbheight uses redux store as it's state! I'm still worried about its impact on performance.... I wonder how textboxes will be like?

* refactored radio buttons

Co-authored-by: Whimpers <kryptocrashmh@gmail.com>