last clean-up of tonight
I'm currently experiencing an error,

"TypeError: instance.render is not a function"

Since it's 1:40, I'll commit whatever I have now, and finish it in the morning.