Reduco Reducere-- to lead back (#23)
* upgrade to expo v38.0.4 lmao

* setValue Action

* expo install react-native-screens

* setup more actions

* clean up

* add eslint

* eslint final

* lint + lintf script

* change eslint parser to babel-eslint

* eslint --fix

* simplify about page

* refactored About page

instead of all those messy <Text> stuff, I made some helper functions. Hopefully this makes the settings page easier to modify.

Also note, "spacer" is not a function.

* remove dead code in Data.js

* last clean-up of tonight

I'm currently experiencing an error,

"TypeError: instance.render is not a function"

Since it's 1:40, I'll commit whatever I have now, and finish it in the morning.

* I swear last cleanup of the night

* fix random error

* install @reduxjs/toolkit@1.4.0

* npm audit fix

* starting the great redux into redux

* basic redux test! :smile:

success!

* structure of store.js

* getting into the flow of redux